version: '2'
services:
  pokedex:
    image: mysql
    container_name: pokedex
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3311:3306
    volumes:
      - pokedex:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

  kanto:
    image: mysql
    container_name: kanto
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - kanto:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

  johto:
    image: mysql
    container_name: johto
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3308:3306
    volumes:
      - johto:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

  hoen:
    image: mysql
    container_name: hoen
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3309:3306
    volumes:
      - hoen:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
 
  kalos:
    image: mysql
    container_name: kalos
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3310:3306
    volumes:
      - kalos:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

volumes:
  pokedex:
  kanto:
  johto:
  hoen:
  kalos:



